### ISSUE TITLE
Why is this a static method and not a prototype method?

### ISSUE THREAD

**Issue by dead-claudia** [NiceLabs/proposal-arraybuffer-equal#1]
I would think a prototype method would be simpler and easier to use. It also fits more in line [with existing userland patterns](https://immutable-js.github.io/immutable-js/docs/#/List/equals).

**Comment by septs** [comment]
1. keep consistent style
[ArrayBuffer.isView](https://mdn.io/ArrayBuffer.isView)

2. allow TypedArray input?
```js
ArrayBuffer.isEquals(Uint8Array.of(0, 0), Uint16Array.of(0))
// vs
Uint8Array.of(0, 0).buffer.equals(Uint16Array.of(0).buffer) // ?
```

**Comment by dead-claudia** [comment]
1. `ArrayBuffer.isView` is a type checking method similar to `Array.isArray`, a different set of idioms.
2. I would expect `ArrayBuffer.isEqual(uint8Array, uint16Array)` to throw as neither argument is an array buffer.

**Comment by septs** [comment]
As a tool method, I think we need to express clear semantics
e.q: https://lodash.com/docs/4.17.15#isEqual

`.equals`, looks more like the prototype method

**Comment by dead-claudia** [comment]
@septs Corrected my example - names are mostly irrelevant for the purposes of my question here.

**Comment by septs** [comment]
OK, No change.

**Comment by septs** [comment]
I will allow TypedArray input.
